# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FateConfig.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='FateConfig.proto',
  package='com.gamehero.sxd2.pro',
  serialized_pb='\n\x10\x46\x61teConfig.proto\x12\x15\x63om.gamehero.sxd2.pro\"\xa4\x01\n\x08\x46\x61teCell\x12\x0e\n\x06\x61ttack\x18\x01 \x01(\r\x12\x0b\n\x03\x64\x65\x66\x18\x02 \x01(\r\x12\x12\n\natt_effect\x18\x03 \x01(\r\x12\x12\n\ndog_effect\x18\x04 \x01(\r\x12\x15\n\rparry_effecta\x18\x05 \x01(\r\x12\x13\n\x0b\x63rit_effect\x18\x06 \x01(\r\x12\x12\n\narp_effect\x18\x07 \x01(\r\x12\x13\n\x0breward_item\x18\x08 \x01(\t\"N\n\x0b\x46\x61teChapter\x12.\n\x05\x63\x65lss\x18\x01 \x03(\x0b\x32\x1f.com.gamehero.sxd2.pro.FateCell\x12\x0f\n\x07taks_id\x18\x02 \x01(\r\"B\n\nFateConfig\x12\x34\n\x08\x63hpaters\x18\x01 \x01(\x0b\x32\".com.gamehero.sxd2.pro.FateChapter')




_FATECELL = _descriptor.Descriptor(
  name='FateCell',
  full_name='com.gamehero.sxd2.pro.FateCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='attack', full_name='com.gamehero.sxd2.pro.FateCell.attack', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='def', full_name='com.gamehero.sxd2.pro.FateCell.def', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='att_effect', full_name='com.gamehero.sxd2.pro.FateCell.att_effect', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dog_effect', full_name='com.gamehero.sxd2.pro.FateCell.dog_effect', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parry_effecta', full_name='com.gamehero.sxd2.pro.FateCell.parry_effecta', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='crit_effect', full_name='com.gamehero.sxd2.pro.FateCell.crit_effect', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arp_effect', full_name='com.gamehero.sxd2.pro.FateCell.arp_effect', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward_item', full_name='com.gamehero.sxd2.pro.FateCell.reward_item', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=44,
  serialized_end=208,
)


_FATECHAPTER = _descriptor.Descriptor(
  name='FateChapter',
  full_name='com.gamehero.sxd2.pro.FateChapter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='celss', full_name='com.gamehero.sxd2.pro.FateChapter.celss', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='taks_id', full_name='com.gamehero.sxd2.pro.FateChapter.taks_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=210,
  serialized_end=288,
)


_FATECONFIG = _descriptor.Descriptor(
  name='FateConfig',
  full_name='com.gamehero.sxd2.pro.FateConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chpaters', full_name='com.gamehero.sxd2.pro.FateConfig.chpaters', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=290,
  serialized_end=356,
)

_FATECHAPTER.fields_by_name['celss'].message_type = _FATECELL
_FATECONFIG.fields_by_name['chpaters'].message_type = _FATECHAPTER
DESCRIPTOR.message_types_by_name['FateCell'] = _FATECELL
DESCRIPTOR.message_types_by_name['FateChapter'] = _FATECHAPTER
DESCRIPTOR.message_types_by_name['FateConfig'] = _FATECONFIG

class FateCell(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FATECELL

  # @@protoc_insertion_point(class_scope:com.gamehero.sxd2.pro.FateCell)

class FateChapter(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FATECHAPTER

  # @@protoc_insertion_point(class_scope:com.gamehero.sxd2.pro.FateChapter)

class FateConfig(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _FATECONFIG

  # @@protoc_insertion_point(class_scope:com.gamehero.sxd2.pro.FateConfig)


# @@protoc_insertion_point(module_scope)
